// src/components/TopBar/TopBar.vue
<template>
  <div id="top-bar" :style="showMenu ? 'max-height: 500px' : 'max-height: 50px'">
    <div class="flex items-center">
      <div class="flex-grow">
        <g-image :src="$static.metadata.githubData.user.avatarUrl" class="avatar" />
        <h4 class="site-name">{{$static.metadata.githubData.user.name}}</h4>
      </div>
      <div class="flex-shrink px-3">
        <button class="btn menu-button" @click="showMenu = !showMenu">
          <v-icon name="bars" label="Menu" scale="2.5" />
        </button>
      </div>
    </div>
    <MenuContent class="mt-16" v-if="showMenu" />
  </div>
</template>

<script>
import "vue-awesome/icons/bars"

import MenuContent from "../MenuContent/MenuContent"

export default {
  data() {
    return {
      showMenu: false,
    }
  },
  components: {
    MenuContent,
  },
}
</script>

<style lang="postcss" scoped>
#top-bar {
  position: fixed;
  top: 0px;
  min-height: 50px;
  width: 100%;
  background: rgb(39, 41, 43);
  color: rgb(204, 204, 204);
  z-index: 100;
  transition: 1s;
  overflow: hidden;

  .menu-closed {
    max-height: 50px;
  }

  .menu-open {
    max-height: 500px;
  }

  .avatar {
    @apply inline rounded-full;
    width: 40px;
    margin-left: 5px;
    padding-top: 5px;
  }

  .site-name {
    @apply ml-4 inline relative;
    top: 5px;
  }

  .menu-button {
    @apply float-right;
    cursor: pointer;
  }
}
</style>

<static-query>
query {
  metadata {
    githubData {
      user {
        name
        avatarUrl
        bio
      }
    }
  }
}
</static-query>

// src/components/TopBar/TopBar.tsx
import React, { useState } from "react"
import { StaticQuery, graphql } from "gatsby"
import MenuContent from "../MenuContent/MenuContent"
import {
  FaBars,
} from "react-icons/fa"
import Button from "../Button/Button"

const TopBar = () => {
  const [showMenu, toggleMenu] = useState<boolean>(false)

  return (
    <StaticQuery
      query={graphql`
        query {
          githubData {
            data {
              user {
                name
                avatarUrl
                bio
              }
            }
          }
          allMarkdownRemark {
            edges {
              node {
                frontmatter {
                  path
                  title
                  date
                }
              }
            }
          }
        }
      `}
      render={data => (
        <div
          style={{
            position: "fixed",
            top: "0px",
            minHeight: "50px",
            maxHeight: !showMenu ? "50px" : "500px",
            width: "100%",
            background: "rgb(39, 41, 43)",
            color: "rgb(204, 204, 204)",
            zIndex: 100,
            transition: "1s",
            overflow: "hidden",
          }}
        >
          <div className="float-left">
            <img
              src={data.githubData.data.user.avatarUrl}
              className="inline rounded-full"
              style={{ width: "40px", marginLeft: "5px", paddingTop: "5px" }}
            />
            <h4
              className="ml-4 inline"
              style={{ position: "relative", top: "5px" }}
            >
              {data.githubData.data.user.name}
            </h4>
          </div>
          <Button
            size="na"
            color="none"
            text="white"
            className="float-right"
            style={{ marginRight: "5px", paddingTop: "5px" }}
            onClick={() => toggleMenu(!showMenu)}
          >
            <FaBars style={{ fontSize: "2.5rem" }} />
          </Button>
          {showMenu && (
            <div className="mt-16">
              <MenuContent />
            </div>
          )}
        </div>
      )}
    />
  )
}
export default TopBar
