// src/pages/Index.vue
<template>
  <Layout>
    <div class="clearfix">
      <div>
        <g-image src="~/images/lindsay-2.jpg" width="968" class="shadow-lg mx-auto block" />
        <h1>Hi, I'm Lindsay Wardell</h1>
        <h3 class="my-4">I'm a software developer and IT professional</h3>
        <h4 class="my-6 text-xl md:text-2xl">
          Helping people get the most out of technology is my passion. I build
          web applications and IT solutions to help people get things done.
        </h4>
      </div>
      <hr class="my-16 mx-auto" />
      <div>
        <div style="margin-top: 10vh">
          <h2 class="text-center">Examples</h2>
          <div class="md:flex">
            <div class="home-card w-full m-auto my-6 md:my-0 md:flex-1 p-2">
              <a href="https://warsofthejuriels.netlify.com">
                <g-image src="~/images/juralen.png" width="400" />
              </a>
            </div>
            <div class="home-card w-full m-auto my-6 md:my-0 md:flex-1 p-2">
              <a href="https://noadjustmentsneeded.com">
                <g-image src="~/images/nan.png" width="400" />
              </a>
            </div>
            <div class="home-card w-full m-auto my-6 md:my-0 md:flex-1 p-2">
              <a href="https://maryspixels.herokuapp.com">
                <g-image src="~/images/marys-pixels.jpg" width="400" />
              </a>
            </div>
          </div>
        </div>
      </div>
      <hr class="my-16 mx-auto" />
      <div>
        <h2 class="text-center">Current Projects</h2>
        <div class="flex flex-wrap">
          <div
            v-for="(node, index) in $page.metadata.githubData.user.repositories.nodes"
            :key="index"
            class="p-2 w-full md:w-1/2"
          >
            <div
              class="p-2 rounded shadow-md bg-white"
              :style="`border: 2px solid ${node.primaryLanguage.color}; min-height: 200px`"
            >
              <span class="md:float-right">{{node.licenseInfo ? node.licenseInfo.name : ""}}</span>
              <h4 class="underline mb-3">
                <a :href="node.url" target="_blank">{{node.name}}</a>
              </h4>
              <span class="italic font-bold">{{node.primaryLanguage.name}}</span>
              <p class="p-5">{{node.description}}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Layout>
</template>

<page-query>
query {
  metadata {
    githubData {
      user {
        name
        avatarUrl
        bio
        repositories {
          nodes {
            description
            name
            url
            licenseInfo {
              name
            }
            primaryLanguage {
              name
              color
            }
          }
        }
      }
    }
  }
}
</page-query>

// src/pages/index.tsx
import React from "react"
import { graphql } from "gatsby"

import Layout from "../components/layout"
import Img from "gatsby-image"
import SEO from "../components/seo"
import Row from "../components/Row/Row"
import Col from "../components/Col/Col"
import Card from "../components/Card/Card"

interface Repository {
  description: string
  name: string
  url: string
  licenseInfo: {
    name: string
  }
  primaryLanguage: {
    name: string
    color: string
  }
}

interface Props {
  data: {
    githubData: {
      data: {
        user: {
          name: string
          bio: string
          avatarUrl: string
          repositories: {
            nodes: Repository[]
          }
        }
      }
    }
    hero: {
      childImageSharp: {
        fluid: any
      }
    }
    project: {
      childImageSharp: {
        fluid: any
      }
    }
    nan: {
      childImageSharp: {
        fluid: any
      }
    }
    mp: {
      childImageSharp: {
        fluid: any
      }
    }
  }
}

const IndexPage = (props: Props) => {
  return (
    <Layout>
      <SEO title="Home" />
      <div className="clearfix">
        <div>
          <Img
            fluid={props.data.hero.childImageSharp.fluid}
            className="shadow-lg"
          />
          <h1>Hi, I'm Lindsay Wardell</h1>
          <h3 className="my-4">I'm a software developer and IT professional</h3>
          <h4 className="my-6 text-xl md:text-2xl">
            Helping people get the most out of technology is my passion. I build
            web applications and IT solutions to help people get things done.
          </h4>
        </div>
        <hr className="my-16" />
        <div>
          <div style={{ marginTop: "10vh" }}>
            <h2 className="text-center">Examples</h2>
            <Row gutter={2} default="inline" className="md:flex">
              <Col className="w-full m-auto my-6 md:my-0 md:flex-1" style={{ maxWidth: "400px" }}>
                <a href="https://warsofthejuriels.netlify.com" target="_blank">
                  <Img
                    fluid={props.data.project.childImageSharp.fluid}
                    className="home-card"
                  />
                </a>
              </Col>
              <Col className="w-full m-auto my-6 md:my-0 md:flex-1" style={{ maxWidth: "400px" }}>
                <a href="https://noadjustmentsneeded.com" target="_blank">
                  <Img
                    fluid={props.data.nan.childImageSharp.fluid}
                    className="home-card"
                  />
                </a>
              </Col>
              <Col className="w-full m-auto my-6 md:my-0 md:flex-1" style={{ maxWidth: "400px" }}>
                <a href="https://maryspixels.herokuapp.com" target="_blank">
                  <Img
                    fluid={props.data.mp.childImageSharp.fluid}
                    className="home-card"
                  />
                </a>
              </Col>
            </Row>
          </div>
        </div>
        <hr className="my-16" />
        <div>
          <h2 className="text-center">Current Projects</h2>
          <Row gutter={2} className="flex-wrap">
            {props.data.githubData.data.user.repositories.nodes.map(
              (node, index) => (
                <Col className="w-full md:w-1/2" key={index}>
                  <Card
                    style={{
                      border: `2px solid ${node.primaryLanguage.color}`,
                      minHeight: "200px",
                    }}
                  >
                    <span className="md:float-right">
                      {node.licenseInfo ? node.licenseInfo.name : ""}
                    </span>
                    <h4 className="underline mb-3">
                      <a href={node.url} target="_blank">
                        {node.name}
                      </a>
                    </h4>
                    <span className="italic font-bold">
                      {node.primaryLanguage.name}
                    </span>
                    <p className="p-5">{node.description}</p>
                  </Card>
                </Col>
              )
            )}
          </Row>
        </div>
      </div>
    </Layout>
  )
}

export default IndexPage

export const pageQuery = graphql`
  query {
    githubData {
      data {
        user {
          name
          avatarUrl
          bio
          repositories {
            nodes {
              description
              name
              url
              licenseInfo {
                name
              }
              primaryLanguage {
                name
                color
              }
            }
          }
        }
      }
    }
    hero: file(relativePath: { eq: "lindsay-2.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 968) {
          ...GatsbyImageSharpFluid
        }
      }
    }
    project: file(relativePath: { eq: "juralen.PNG" }) {
      childImageSharp {
        fluid(maxWidth: 500) {
          ...GatsbyImageSharpFluid
        }
      }
    }
    nan: file(relativePath: { eq: "nan.png" }) {
      childImageSharp {
        fluid(maxWidth: 500) {
          ...GatsbyImageSharpFluid
        }
      }
    }
    mp: file(relativePath: { eq: "mp.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 500) {
          ...GatsbyImageSharpFluid
        }
      }
    }
  }
`
